# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrole.proto\x12\x04role\" \n\x04Role\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x11\n\x0fRoleListRequest\",\n\x10RoleListResponse\x12\x18\n\x04role\x18\x01 \x03(\x0b\x32\n.role.Role\"\x1f\n\x11RoleDetailRequest\x12\n\n\x02id\x18\x01 \x01(\x05\".\n\x12RoleDetailResponse\x12\x18\n\x04role\x18\x01 \x01(\x0b\x32\n.role.Role\"!\n\x11RoleCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x12RoleCreateResponse\x12\x18\n\x04role\x18\x01 \x01(\x0b\x32\n.role.Role\"-\n\x11RoleUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\".\n\x12RoleUpdateResponse\x12\x18\n\x04role\x18\x01 \x01(\x0b\x32\n.role.Role\"\x1f\n\x11RoleDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12RoleDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb5\x02\n\x0bRoleService\x12\x35\n\x04list\x12\x15.role.RoleListRequest\x1a\x16.role.RoleListResponse\x12\x38\n\x03get\x12\x17.role.RoleDetailRequest\x1a\x18.role.RoleDetailResponse\x12;\n\x06\x63reate\x12\x17.role.RoleCreateRequest\x1a\x18.role.RoleCreateResponse\x12;\n\x06update\x12\x17.role.RoleUpdateRequest\x1a\x18.role.RoleUpdateResponse\x12;\n\x06\x64\x65lete\x12\x17.role.RoleDeleteRequest\x1a\x18.role.RoleDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'role_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROLE']._serialized_start=20
  _globals['_ROLE']._serialized_end=52
  _globals['_ROLELISTREQUEST']._serialized_start=54
  _globals['_ROLELISTREQUEST']._serialized_end=71
  _globals['_ROLELISTRESPONSE']._serialized_start=73
  _globals['_ROLELISTRESPONSE']._serialized_end=117
  _globals['_ROLEDETAILREQUEST']._serialized_start=119
  _globals['_ROLEDETAILREQUEST']._serialized_end=150
  _globals['_ROLEDETAILRESPONSE']._serialized_start=152
  _globals['_ROLEDETAILRESPONSE']._serialized_end=198
  _globals['_ROLECREATEREQUEST']._serialized_start=200
  _globals['_ROLECREATEREQUEST']._serialized_end=233
  _globals['_ROLECREATERESPONSE']._serialized_start=235
  _globals['_ROLECREATERESPONSE']._serialized_end=281
  _globals['_ROLEUPDATEREQUEST']._serialized_start=283
  _globals['_ROLEUPDATEREQUEST']._serialized_end=328
  _globals['_ROLEUPDATERESPONSE']._serialized_start=330
  _globals['_ROLEUPDATERESPONSE']._serialized_end=376
  _globals['_ROLEDELETEREQUEST']._serialized_start=378
  _globals['_ROLEDELETEREQUEST']._serialized_end=409
  _globals['_ROLEDELETERESPONSE']._serialized_start=411
  _globals['_ROLEDELETERESPONSE']._serialized_end=448
  _globals['_ROLESERVICE']._serialized_start=451
  _globals['_ROLESERVICE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
