# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\x12\x04item\"4\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nkategoriId\x18\x03 \x01(\t\"\x11\n\x0fItemListRequest\",\n\x10ItemListResponse\x12\x18\n\x04Item\x18\x01 \x03(\x0b\x32\n.item.Item\"\x1f\n\x11ItemDetailRequest\x12\n\n\x02id\x18\x01 \x01(\x05\".\n\x12ItemDetailResponse\x12\x18\n\x04item\x18\x01 \x01(\x0b\x32\n.item.Item\"5\n\x11ItemCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nkategoriId\x18\x02 \x01(\t\".\n\x12ItemCreateResponse\x12\x18\n\x04item\x18\x01 \x01(\x0b\x32\n.item.Item\"-\n\x11ItemUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"?\n\x12ItemUpdateResponse\x12\x18\n\x04item\x18\x01 \x01(\x0b\x32\n.item.Item\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x11ItemDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12ItemDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb8\x02\n\x0bItemService\x12\x35\n\x04list\x12\x15.item.ItemListRequest\x1a\x16.item.ItemListResponse\x12;\n\x06\x64\x65tail\x12\x17.item.ItemDetailRequest\x1a\x18.item.ItemDetailResponse\x12;\n\x06\x63reate\x12\x17.item.ItemCreateRequest\x1a\x18.item.ItemCreateResponse\x12;\n\x06update\x12\x17.item.ItemUpdateRequest\x1a\x18.item.ItemUpdateResponse\x12;\n\x06\x64\x65lete\x12\x17.item.ItemDeleteRequest\x1a\x18.item.ItemDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=20
  _globals['_ITEM']._serialized_end=72
  _globals['_ITEMLISTREQUEST']._serialized_start=74
  _globals['_ITEMLISTREQUEST']._serialized_end=91
  _globals['_ITEMLISTRESPONSE']._serialized_start=93
  _globals['_ITEMLISTRESPONSE']._serialized_end=137
  _globals['_ITEMDETAILREQUEST']._serialized_start=139
  _globals['_ITEMDETAILREQUEST']._serialized_end=170
  _globals['_ITEMDETAILRESPONSE']._serialized_start=172
  _globals['_ITEMDETAILRESPONSE']._serialized_end=218
  _globals['_ITEMCREATEREQUEST']._serialized_start=220
  _globals['_ITEMCREATEREQUEST']._serialized_end=273
  _globals['_ITEMCREATERESPONSE']._serialized_start=275
  _globals['_ITEMCREATERESPONSE']._serialized_end=321
  _globals['_ITEMUPDATEREQUEST']._serialized_start=323
  _globals['_ITEMUPDATEREQUEST']._serialized_end=368
  _globals['_ITEMUPDATERESPONSE']._serialized_start=370
  _globals['_ITEMUPDATERESPONSE']._serialized_end=433
  _globals['_ITEMDELETEREQUEST']._serialized_start=435
  _globals['_ITEMDELETEREQUEST']._serialized_end=466
  _globals['_ITEMDELETERESPONSE']._serialized_start=468
  _globals['_ITEMDELETERESPONSE']._serialized_end=505
  _globals['_ITEMSERVICE']._serialized_start=508
  _globals['_ITEMSERVICE']._serialized_end=820
# @@protoc_insertion_point(module_scope)
