# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kategori.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekategori.proto\x12\x08kategori\"(\n\x08Kategori\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08kategori\x18\x02 \x01(\t\"\x15\n\x13KategoriListRequest\"<\n\x14KategoriListResponse\x12$\n\x08kategori\x18\x01 \x03(\x0b\x32\x12.kategori.Kategori\"#\n\x15KategoriDetailRequest\x12\n\n\x02id\x18\x01 \x01(\x05\">\n\x16KategoriDetailResponse\x12$\n\x08kategori\x18\x01 \x01(\x0b\x32\x12.kategori.Kategori\")\n\x15KategoriCreateRequest\x12\x10\n\x08kategori\x18\x01 \x01(\t\">\n\x16KategoriCreateResponse\x12$\n\x08kategori\x18\x01 \x01(\x0b\x32\x12.kategori.Kategori\"5\n\x15KategoriUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08kategori\x18\x02 \x01(\t\"O\n\x16KategoriUpdateResponse\x12$\n\x08kategori\x18\x01 \x01(\x0b\x32\x12.kategori.Kategori\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x15KategoriDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x16KategoriDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x89\x03\n\x0fKategoriService\x12\x45\n\x04list\x12\x1d.kategori.KategoriListRequest\x1a\x1e.kategori.KategoriListResponse\x12H\n\x03get\x12\x1f.kategori.KategoriDetailRequest\x1a .kategori.KategoriDetailResponse\x12K\n\x06\x63reate\x12\x1f.kategori.KategoriCreateRequest\x1a .kategori.KategoriCreateResponse\x12K\n\x06update\x12\x1f.kategori.KategoriUpdateRequest\x1a .kategori.KategoriUpdateResponse\x12K\n\x06\x64\x65lete\x12\x1f.kategori.KategoriDeleteRequest\x1a .kategori.KategoriDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kategori_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KATEGORI']._serialized_start=28
  _globals['_KATEGORI']._serialized_end=68
  _globals['_KATEGORILISTREQUEST']._serialized_start=70
  _globals['_KATEGORILISTREQUEST']._serialized_end=91
  _globals['_KATEGORILISTRESPONSE']._serialized_start=93
  _globals['_KATEGORILISTRESPONSE']._serialized_end=153
  _globals['_KATEGORIDETAILREQUEST']._serialized_start=155
  _globals['_KATEGORIDETAILREQUEST']._serialized_end=190
  _globals['_KATEGORIDETAILRESPONSE']._serialized_start=192
  _globals['_KATEGORIDETAILRESPONSE']._serialized_end=254
  _globals['_KATEGORICREATEREQUEST']._serialized_start=256
  _globals['_KATEGORICREATEREQUEST']._serialized_end=297
  _globals['_KATEGORICREATERESPONSE']._serialized_start=299
  _globals['_KATEGORICREATERESPONSE']._serialized_end=361
  _globals['_KATEGORIUPDATEREQUEST']._serialized_start=363
  _globals['_KATEGORIUPDATEREQUEST']._serialized_end=416
  _globals['_KATEGORIUPDATERESPONSE']._serialized_start=418
  _globals['_KATEGORIUPDATERESPONSE']._serialized_end=497
  _globals['_KATEGORIDELETEREQUEST']._serialized_start=499
  _globals['_KATEGORIDELETEREQUEST']._serialized_end=534
  _globals['_KATEGORIDELETERESPONSE']._serialized_start=536
  _globals['_KATEGORIDELETERESPONSE']._serialized_end=577
  _globals['_KATEGORISERVICE']._serialized_start=580
  _globals['_KATEGORISERVICE']._serialized_end=973
# @@protoc_insertion_point(module_scope)
