# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rack.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrack.proto\x12\x04rack\" \n\x04Rack\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x11\n\x0fRackListRequest\",\n\x10RackListResponse\x12\x18\n\x04rack\x18\x01 \x03(\x0b\x32\n.rack.Rack\"\x1f\n\x11RackDetailRequest\x12\n\n\x02id\x18\x01 \x01(\x05\".\n\x12RackDetailResponse\x12\x18\n\x04rack\x18\x01 \x01(\x0b\x32\n.rack.Rack\"!\n\x11RackCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x12RackCreateResponse\x12\x18\n\x04rack\x18\x01 \x01(\x0b\x32\n.rack.Rack\"-\n\x11RackUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"?\n\x12RackUpdateResponse\x12\x18\n\x04rack\x18\x01 \x01(\x0b\x32\n.rack.Rack\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x11RackDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"?\n\x12RackDeleteResponse\x12\x18\n\x04rack\x18\x01 \x01(\x0b\x32\n.rack.Rack\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x13ItemRackListRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xb5\x02\n\x0bRackService\x12\x35\n\x04list\x12\x15.rack.RackListRequest\x1a\x16.rack.RackListResponse\x12\x38\n\x03get\x12\x17.rack.RackDetailRequest\x1a\x18.rack.RackDetailResponse\x12;\n\x06\x63reate\x12\x17.rack.RackCreateRequest\x1a\x18.rack.RackCreateResponse\x12;\n\x06update\x12\x17.rack.RackUpdateRequest\x1a\x18.rack.RackUpdateResponse\x12;\n\x06\x64\x65lete\x12\x17.rack.RackDeleteRequest\x1a\x18.rack.RackDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rack_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RACK']._serialized_start=20
  _globals['_RACK']._serialized_end=52
  _globals['_RACKLISTREQUEST']._serialized_start=54
  _globals['_RACKLISTREQUEST']._serialized_end=71
  _globals['_RACKLISTRESPONSE']._serialized_start=73
  _globals['_RACKLISTRESPONSE']._serialized_end=117
  _globals['_RACKDETAILREQUEST']._serialized_start=119
  _globals['_RACKDETAILREQUEST']._serialized_end=150
  _globals['_RACKDETAILRESPONSE']._serialized_start=152
  _globals['_RACKDETAILRESPONSE']._serialized_end=198
  _globals['_RACKCREATEREQUEST']._serialized_start=200
  _globals['_RACKCREATEREQUEST']._serialized_end=233
  _globals['_RACKCREATERESPONSE']._serialized_start=235
  _globals['_RACKCREATERESPONSE']._serialized_end=281
  _globals['_RACKUPDATEREQUEST']._serialized_start=283
  _globals['_RACKUPDATEREQUEST']._serialized_end=328
  _globals['_RACKUPDATERESPONSE']._serialized_start=330
  _globals['_RACKUPDATERESPONSE']._serialized_end=393
  _globals['_RACKDELETEREQUEST']._serialized_start=395
  _globals['_RACKDELETEREQUEST']._serialized_end=426
  _globals['_RACKDELETERESPONSE']._serialized_start=428
  _globals['_RACKDELETERESPONSE']._serialized_end=491
  _globals['_ITEMRACKLISTREQUEST']._serialized_start=493
  _globals['_ITEMRACKLISTREQUEST']._serialized_end=526
  _globals['_RACKSERVICE']._serialized_start=529
  _globals['_RACKSERVICE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
