# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rack_pb2 as rack__pb2


class RackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list = channel.unary_unary(
                '/rack.RackService/list',
                request_serializer=rack__pb2.RackListRequest.SerializeToString,
                response_deserializer=rack__pb2.RackListResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/rack.RackService/get',
                request_serializer=rack__pb2.RackDetailRequest.SerializeToString,
                response_deserializer=rack__pb2.RackDetailResponse.FromString,
                )
        self.create = channel.unary_unary(
                '/rack.RackService/create',
                request_serializer=rack__pb2.RackCreateRequest.SerializeToString,
                response_deserializer=rack__pb2.RackCreateResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/rack.RackService/update',
                request_serializer=rack__pb2.RackUpdateRequest.SerializeToString,
                response_deserializer=rack__pb2.RackUpdateResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/rack.RackService/delete',
                request_serializer=rack__pb2.RackDeleteRequest.SerializeToString,
                response_deserializer=rack__pb2.RackDeleteResponse.FromString,
                )


class RackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list': grpc.unary_unary_rpc_method_handler(
                    servicer.list,
                    request_deserializer=rack__pb2.RackListRequest.FromString,
                    response_serializer=rack__pb2.RackListResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=rack__pb2.RackDetailRequest.FromString,
                    response_serializer=rack__pb2.RackDetailResponse.SerializeToString,
            ),
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=rack__pb2.RackCreateRequest.FromString,
                    response_serializer=rack__pb2.RackCreateResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=rack__pb2.RackUpdateRequest.FromString,
                    response_serializer=rack__pb2.RackUpdateResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=rack__pb2.RackDeleteRequest.FromString,
                    response_serializer=rack__pb2.RackDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rack.RackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rack.RackService/list',
            rack__pb2.RackListRequest.SerializeToString,
            rack__pb2.RackListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rack.RackService/get',
            rack__pb2.RackDetailRequest.SerializeToString,
            rack__pb2.RackDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rack.RackService/create',
            rack__pb2.RackCreateRequest.SerializeToString,
            rack__pb2.RackCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rack.RackService/update',
            rack__pb2.RackUpdateRequest.SerializeToString,
            rack__pb2.RackUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rack.RackService/delete',
            rack__pb2.RackDeleteRequest.SerializeToString,
            rack__pb2.RackDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
