# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kategori_pb2 as kategori__pb2


class KategoriServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list = channel.unary_unary(
                '/kategori.KategoriService/list',
                request_serializer=kategori__pb2.KategoriListRequest.SerializeToString,
                response_deserializer=kategori__pb2.KategoriListResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/kategori.KategoriService/get',
                request_serializer=kategori__pb2.KategoriDetailRequest.SerializeToString,
                response_deserializer=kategori__pb2.KategoriDetailResponse.FromString,
                )
        self.create = channel.unary_unary(
                '/kategori.KategoriService/create',
                request_serializer=kategori__pb2.KategoriCreateRequest.SerializeToString,
                response_deserializer=kategori__pb2.KategoriCreateResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/kategori.KategoriService/update',
                request_serializer=kategori__pb2.KategoriUpdateRequest.SerializeToString,
                response_deserializer=kategori__pb2.KategoriUpdateResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/kategori.KategoriService/delete',
                request_serializer=kategori__pb2.KategoriDeleteRequest.SerializeToString,
                response_deserializer=kategori__pb2.KategoriDeleteResponse.FromString,
                )


class KategoriServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KategoriServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list': grpc.unary_unary_rpc_method_handler(
                    servicer.list,
                    request_deserializer=kategori__pb2.KategoriListRequest.FromString,
                    response_serializer=kategori__pb2.KategoriListResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=kategori__pb2.KategoriDetailRequest.FromString,
                    response_serializer=kategori__pb2.KategoriDetailResponse.SerializeToString,
            ),
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=kategori__pb2.KategoriCreateRequest.FromString,
                    response_serializer=kategori__pb2.KategoriCreateResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=kategori__pb2.KategoriUpdateRequest.FromString,
                    response_serializer=kategori__pb2.KategoriUpdateResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=kategori__pb2.KategoriDeleteRequest.FromString,
                    response_serializer=kategori__pb2.KategoriDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kategori.KategoriService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KategoriService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kategori.KategoriService/list',
            kategori__pb2.KategoriListRequest.SerializeToString,
            kategori__pb2.KategoriListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kategori.KategoriService/get',
            kategori__pb2.KategoriDetailRequest.SerializeToString,
            kategori__pb2.KategoriDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kategori.KategoriService/create',
            kategori__pb2.KategoriCreateRequest.SerializeToString,
            kategori__pb2.KategoriCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kategori.KategoriService/update',
            kategori__pb2.KategoriUpdateRequest.SerializeToString,
            kategori__pb2.KategoriUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kategori.KategoriService/delete',
            kategori__pb2.KategoriDeleteRequest.SerializeToString,
            kategori__pb2.KategoriDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
